apiVersion: v1
kind: Service
metadata:
  name: service-example-backend
spec:
  selector:
    app: service-example-backend
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-example-backend
spec:
  rules:
    - host: service-example-backend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-example-backend
                port:
                  number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-example-backend
spec:
  selector:
    matchLabels:
      app: service-example-backend
  template:
    metadata:
      labels:
        app: service-example-backend
    spec:
      containers:
        - name: service-example-backend
          image: localhost:5000/service-example-backend:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 800Mi
            requests:
              cpu: 500m
              memory: 300Mi
          env:
            - name: PORT
              value: "3000"
